[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
solc = "0.8.19"     # Choose your preferred Solidity version

# Optimization settings
optimizer = true
optimizer_runs = 200

# Testing settings
verbosity = 2
fuzz_runs = 1000
gas_reports = ["*"]

# Development settings
auto_detect_solc = true
block_timestamp = 1_680_220_800  # 2023-03-31
chain_id = 1

# Libraries
libraries = []

[rpc_endpoints]
mainnet = "${MAINNET_RPC_URL}"
goerli = "${GOERLI_RPC_URL}"
